// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_render from "./routes/_render.ts";
import * as $index from "./routes/index.tsx";
import * as $App from "./islands/App.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_render.ts": $_render,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/App.tsx": $App,
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
